dataset_dir: "/home/rpg_staff/giovanni/gvi-fusion/results/imu_simulator/sim_lemniscate_blackpc"

# Num. of seqs in the dataset to be created
n_seq: 4573

## Parameters
# groundtruth
gt_freq: 400 # Hz

# imu
imu_freq: 400
use_filtered_imu: false

# Parameters for create_dataset_txt_format.py
traj_fn: "trajectory.txt"
vel_fn: "velocity.txt"

# Parameters for create_dataset_binary_format.py
# how to split the n_seq sequences
perc_train: 70
perc_val: 20
perc_test: 10
