dataset_dir: "/home/giovanni/TLIO/data/sim/cpc3_3"

# Num. of seqs in the dataset to be created
n_seq: 1000

## Parameters
# groundtruth
gt_freq: 500 # Hz

# imu
imu_freq: 500
use_filtered_imu: false

# Parameters for create_dataset_txt_format.py
traj_fn: "trajectory.txt"
vel_fn: "velocity.txt"

# Parameters for create_dataset_binary_format.py
# how to split the n_seq sequences
perc_train: 70
perc_val: 20
perc_test: 10
